{
	"id": "CVE-2021-3737",
	"description": "A flaw was found in python. An improperly handled HTTP response in the HTTP client code of python may allow a remote attacker, who controls the HTTP server, to make the client script enter an infinite loop, consuming CPU time. The highest threat from this vulnerability is to system availability.",
	"scope": "local",
	"packages": [
		{
			"name": "pypy3",
			"status": "resolved",
			"urgency": "not yet assigned",
			"fixed_version": "7.3.5+dfsg-2+deb11u4",
			"repository": [
				{
					"name": "bullseye",
					"version": "7.3.5+dfsg-2+deb11u2"
				},
				{
					"name": "bullseye-security",
					"version": "7.3.5+dfsg-2+deb11u4"
				}
			]
		},
		{
			"name": "python2.7",
			"status": "open",
			"nodsa": "Unsupported in Bullseye, only included to build a few applications",
			"nodsa_reason": "ignored",
			"urgency": "not yet assigned",
			"repository": [
				{
					"name": "bullseye",
					"version": "2.7.18-8+deb11u1"
				}
			]
		},
		{
			"name": "python3.9",
			"status": "resolved",
			"urgency": "not yet assigned",
			"fixed_version": "3.9.2-1+deb11u2",
			"repository": [
				{
					"name": "bullseye",
					"version": "3.9.2-1"
				},
				{
					"name": "bullseye-security",
					"version": "3.9.2-1+deb11u2"
				}
			]
		}
	]
}
