{
  "id": "CVE-2023-29935",
  "description": "llvm-project commit a0138390 was discovered to contain an assertion failure at !replacements.count(op) && \"operation was already replaced.",
  "scope": "local",
  "packages": [
    {
      "name": "llvm-toolchain-14",
      "status": "open",
      "urgency": "unimportant",
      "repository": [
        {
          "name": "trixie",
          "version": "1:14.0.6-16"
        }
      ]
    },
    {
      "name": "llvm-toolchain-13",
      "status": "open",
      "urgency": "unimportant",
      "repository": [
        {
          "name": "trixie",
          "version": "1:13.0.1-13"
        }
      ]
    },
    {
      "name": "llvm-toolchain-15",
      "status": "open",
      "urgency": "unimportant",
      "repository": [
        {
          "name": "trixie",
          "version": "1:15.0.7-10"
        }
      ]
    }
  ]
}
