{
	"id": "CVE-2022-23097",
	"description": "An issue was discovered in the DNS proxy in Connman through 1.40. forward_dns_reply mishandles a strnlen call, leading to an out-of-bounds read.",
	"debian_bug": 1004935,
	"scope": "local",
	"packages": [
		{
			"name": "connman",
			"status": "resolved",
			"urgency": "not yet assigned",
			"fixed_version": "1.36-2.1~deb10u4",
			"repository": [
				{
					"name": "buster",
					"version": "1.36-2.1~deb10u2"
				},
				{
					"name": "buster-security",
					"version": "1.36-2.1~deb10u5"
				}
			]
		}
	]
}
