{
	"id": "CVE-2015-5145",
	"description": "validators.URLValidator in Django 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (CPU consumption) via unspecified vectors.",
	"scope": "local",
	"packages": [
		{
			"name": "python-django",
			"status": "resolved",
			"urgency": "unimportant",
			"fixed_version": "0",
			"repository": [
				{
					"name": "bullseye-security",
					"version": "2:2.2.28-1~deb11u2"
				},
				{
					"name": "bullseye",
					"version": "2:2.2.28-1~deb11u2"
				}
			]
		}
	]
}
