{
	"id": "CVE-2023-36053",
	"description": "In Django 3.2 before 3.2.20, 4 before 4.1.10, and 4.2 before 4.2.3, EmailValidator and URLValidator are subject to a potential ReDoS (regular expression denial of service) attack via a very large number of domain name labels of emails and URLs.",
	"debian_bug": 1040225,
	"scope": "local",
	"packages": [
		{
			"name": "python-django",
			"status": "resolved",
			"urgency": "not yet assigned",
			"fixed_version": "2:2.2.28-1~deb11u2",
			"repository": [
				{
					"name": "bullseye",
					"version": "2:2.2.28-1~deb11u2"
				},
				{
					"name": "bullseye-security",
					"version": "2:2.2.28-1~deb11u3"
				}
			]
		}
	]
}
