{
	"id": "CVE-2023-49081",
	"debian_bug": 1057163,
	"packages": [
		{
			"name": "python-aiohttp",
			"status": "open",
			"urgency": "not yet assigned",
			"repository": [
				{
					"name": "sid",
					"version": "3.8.6-1"
				}
			]
		}
	]
}
