{
	"id": "CVE-2022-48560",
	"description": "A use-after-free exists in Python through 3.9 via heappushpop in heapq.",
	"scope": "local",
	"packages": [
		{
			"name": "python2.7",
			"status": "resolved",
			"urgency": "not yet assigned",
			"fixed_version": "2.7.18-8+deb11u1",
			"repository": [
				{
					"name": "bullseye",
					"version": "2.7.18-8+deb11u1"
				}
			]
		},
		{
			"name": "python3.9",
			"status": "resolved",
			"urgency": "unimportant",
			"fixed_version": "0",
			"repository": [
				{
					"name": "bullseye-security",
					"version": "3.9.2-1+deb11u2"
				},
				{
					"name": "bullseye",
					"version": "3.9.2-1"
				}
			]
		}
	]
}
